/**
 * The API bundle is generated by the build (see vercel.json), so it is absent
 * from a source checkout. Declaring its shape keeps `tsc --noEmit` honest
 * either way: without this the import errors on a clean tree, and with a
 * @ts-expect-error instead it errors *after* a build, when the directive turns
 * out to be unused (TS2578, which the Vercel build log duly reported).
 */
declare module "*/_api-bundle.js" {
  const app: { fetch(request: Request): Response | Promise<Response> };
  export default app;
}
